services:
  - type: web
    name: phone-finder
    runtime: docker
    plan: free # Can use free plan now since no disk
    region: singapore # Asia Pacific
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://phone-finder.onrender.com # Update after deployment
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
